#
# Executes commands at login pre-zshrc.
#

# Fix SSH/GPG agent issues on NixOS:
if command -v gpgconf >/dev/null 2>&1; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

export GOPATH=$HOME/Developer/go

# Browser
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Editors
export EDITOR='vim'
if [ -x "$(command -v nvim)" ]; then
  export EDITOR='nvim'
fi

export VISUAL="$EDITOR"
export GIT_EDITOR="$EDITOR"
export PAGER='less'

export LESS='-i -R -w -F'

# Paths
path=(
  $HOME/bin
  $HOME/.npm-packages/bin
  $path
)

# Set the the list of directories that cd searches.
cdpath=(
  $HOME/Sites
  $HOME/Developer
  $cdpath
)

# Allow Ctrl-S to be used as binding
stty -ixon

if [ -f "$HOME/.zprofile.local" ]; then
  source $HOME/.zprofile.local
fi

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
