#
# Executes commands at login pre-zshrc.
#

# Tmux
# Set $TERM explicitly to force tmux to recognize 256 colors
export TERM=screen-256color-bce

# Browser
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi


# Editors
export VISUAL=vim
export EDITOR=vim
export GIT_EDITOR=vim
export PAGER='less'


# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi


# Paths
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path


# Set the the list of directories that cd searches.
cdpath=(
  $HOME/Sites 
  $cdpath
)


# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.rbenv/shims 
  $HOME/.nodenv/bin
  /usr/local/{bin,sbin}
  /{bin,sbin}
  /usr/{bin,sbin}
  $path
)

# add homebrew PHP to path
export PATH="$(brew --prefix josegonzalez/php/php55)/bin:$PATH"


# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi


# Temporary Files
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

# Allow Ctrl-S to be used as binding
stty -ixon
