#
# Executes commands at login pre-zshrc.
#

export GPG_TTY=$(tty)

export GOPATH=$HOME/Developer/go

# Browser
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Editors
export VISUAL='vim'
export EDITOR='vim'
export GIT_EDITOR='vim'
export PAGER='less'

# Paths
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
cdpath=(
  $HOME/Sites 
  $HOME/Developer
  $cdpath
)

# Set the list of directories that Zsh searches for programs.
path=(
	$HOME/.cargo/bin
	/usr/local/opt/php@7.0/bin
	/usr/local/opt/php@7.0/sbin
	$HOME/Library/Python/3.6/bin
	$HOME/Library/Python/2.7/bin
	${GOPATH//://bin:}/bin
	$HOME/.composer/vendor/bin
	$HOME/.rbenv/bin
	/usr/local/{bin,sbin}
	/{bin,sbin}
	/usr/{bin,sbin}
	$path
)

# rbenv
if [ -x "$(command -v rbenv)" ]; then
	eval "$(rbenv init -)"
fi

# Set the default Less options.
export LESS='-i -R -w -X -F'

# Enable syntax highlighting when viewing files with Less.
# <http://ole.michelsen.dk/blog/syntax-highlight-files-macos-terminal-less.html>
LESSPIPE=`which src-hilite-lesspipe.sh`
export LESSOPEN="| ${LESSPIPE} %s"

# Allow Ctrl-S to be used as binding
stty -ixon
