#
# Executes commands at login pre-zshrc.
#

export GPG_TTY=$(tty)

export GOPATH=$HOME/Developer/go

# Browser
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Editors
export VISUAL='vim'
export EDITOR='vim'
export GIT_EDITOR='vim'
export PAGER='less'

export LESS='-i -R -w -F'

# Paths
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
cdpath=(
  $HOME/Sites 
  $HOME/Developer
  $cdpath
)

# Set the list of directories that Zsh searches for programs.
path=(
	/usr/local/{bin,sbin}
	/{bin,sbin}
	/usr/{bin,sbin}
	$path
)

# Allow Ctrl-S to be used as binding
stty -ixon

if [ -f "$HOME/.zprofile.local" ]; then
  source $HOME/.zprofile.local
fi
