#
# Defines environment variables.
#

# Zprezto: Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# set up rbenv
eval "$(rbenv init - zsh)"

# set up nodenv
eval "$(nodenv init -)"

# set up php-version
source $(brew --prefix php-version)/php-version.sh && php-version 5
