#
# Executes commands at the start of an interactive session.
#


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# VIM MODE
set -o vi

# completion
# case-insensitive (all),partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' \
    'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
set completion-ignore-case On

# Fancy Ctrl-Z
# from: http://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# Load aliases
alias aliases='vi $HOME/.dotfiles/zsh/aliases.zsh'
source "$HOME/.dotfiles/zsh/aliases.zsh"

# Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
