#
# Executes commands at the start of an interactive session.
#

# Quickly change directories (e.g. $ foo --> $ cd foo)
setopt auto_cd 

# enable history
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE="$HOME/.zsh_history"

# Share history between tabs, and avoid writing
# duplicate records if same command is re-run.
setopt share_history
setopt hist_ignore_dups
setopt hist_reduce_blanks

# Read system metadata, if applicable:
{ export DEVBOX_NAME=$(< /pay/conf/box-name); } 2> /dev/null
{ export DEVBOX_EMOJI=$(< /pay/conf/box-emoji); } 2> /dev/null

# FZF shell integration (homebrew):
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# FZF shell integration (nix):
if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi

# Load aliases & bindings:
source "$HOME/.dotfiles/zsh/bindings.zsh"
source "$HOME/.dotfiles/zsh/aliases.zsh"

# Source bash aliases if they exist:
[ -f ~/.bash_aliases ] && source ~/.bash_aliases

# Quick edit:
function zshrc() { vi $HOME/.dotfiles/zsh/zshrc && source ~/.zshrc }
function aliases() { vi $HOME/.dotfiles/zsh/aliases.zsh && source ~/.zshrc }
function bindings() { vi $HOME/.dotfiles/zsh/bindings.zsh && source ~/.zshrc }

# Starship prompt <https://starship.rs>:
eval "$(starship init zsh)"
# source "/opt/homebrew/opt/spaceship/spaceship.zsh"

# Bat (cat clone):
export BAT_PAGER='less -RF'
export BAT_STYLE='numbers,changes'

# Enable any Homebrew completions (if installed):
# Note: This must be done before compinit is called.
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# Completion:
# case-insensitive (all), partial-word and then substring completion
autoload -U compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' \
    'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
set completion-ignore-case On

# make completion speedier
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending

# Syntax highlighting
if [ -f "/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
  source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  ZSH_HIGHLIGHT_STYLES[unknown-token]='none'
  ZSH_HIGHLIGHT_STYLES[precommand]='fg=yellow,underline'
  ZSH_HIGHLIGHT_STYLES[command]='fg=yellow'
  ZSH_HIGHLIGHT_STYLES[alias]='fg=yellow'
  ZSH_HIGHLIGHT_STYLES[builtin]='fg=yellow'
  ZSH_HIGHLIGHT_STYLES[function]='fg=yellow'
  ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=green'
  ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=green'
fi

# Enable iTerm2 shell integration (if installed):
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# Enable rbenv & pyenv (if installed):
if [ -x "$(command -v rbenv)" ]; then
  eval "$(rbenv init -)"
fi

if [ -x "$(command -v nodenv)" ]; then
  eval "$(nodenv init -)"
fi

if [ -x "$(command -v pyenv)" ]; then
  eval "$(pyenv init -)"
fi

# Run additional customizations:
if [ -f "$HOME/.zshrc.local" ]; then
  source $HOME/.zshrc.local
fi
