#
# Executes commands at the start of an interactive session.
#


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# set up rbenv
eval "$(rbenv init - zsh)"

# set up nodenv
eval "$(nodenv init -)"

# set up php-version
source $(brew --prefix php-version)/php-version.sh && php-version 5

# VIM MODE
set -o vi

# completion
# case-insensitive (all),partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' \
    'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
set completion-ignore-case On


# Fixes completion issues on certain tools
alias bower='noglob bower'

# Basic aliases
alias l="ls -GFh"
alias ls="ls -GFh"
alias ll="ls -GFhl"

alias t="tree -L 2 -I node_modules"
alias tl="tree -I node_modules"

alias ...="cd ../.."
alias ....="cd ../../.."

alias http="http-server"


# Searching aliases
function findd() { find . -name $* -type d } # usage: findd "regex_string"; ex: findd "*neue*"
function findf() { grep -nr $* . }  # usage: findf "search_string"


# OS X aliases
alias ql='qlmanage -p "$@" & > /dev/null'
alias oo="open ." # open current directory in OS X Finder
function port() { sudo lsof -i :$*; } # check what's running on this port
function trash() { mv $1 ~/.Trash } # move file to the trash

# open multiple vim files in tabs
alias vi="vim -p"
alias vim="vim -p"
alias mvim="mvim -p"


# Clear alias
alias c="clear"

# Vagrant aliases
alias v="vagrant"
alias vst="vagrant status"
alias vup="vagrant up"
alias vsp="vagrant suspend"
alias vre="vagrant halt && vagrant reload"

ds() { vagrant ssh -c "cd /vagrant && ds $*" }
drush() { v ssh -c "cd /vagrant/html && drush $*" }
neue-sync() {
  cd $HOME/Sites/neue
  grunt prod

  rm -rf $HOME/Sites/dosomething/lib/themes/dosomething/paraneue_dosomething/bower_components/neue
  mkdir $HOME/Sites/dosomething/lib/themes/dosomething/paraneue_dosomething/bower_components/neue
  cp -r dist/* $HOME/Sites/dosomething/lib/themes/dosomething/paraneue_dosomething/bower_components/neue

  cd -

  echo "Built dist package and copied into DS app."
}


# Git aliases
alias g="git"
alias gs="git status"
alias gst="git status -sb"
alias ga="git add"
alias gc="git commit"
alias gdiff="git diff"
alias gb="git branch"
alias gch="git checkout"
alias gcb="git checkout -b"
alias glg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glgg="git log"
alias gp="git push"
alias gpl="git pull"
alias gclean="git fetch --prune --all && git branch --merged dev | grep -v 'dev' | xargs git branch -d && git branch"
ghub() {
  hub browse
}
gpr() {
  hub browse -- compare/$(git-branch-current)
}
gpu() { git push --set-upstream origin $(git-branch-current) } 
gpuf() { git push --set-upstream origin $(git-branch-current) --force } 
gsync() { git fetch upstream && git checkout dev && git rebase upstream/dev && git push origin dev } 

# misc aliases
alias be="bundle exec"
alias sass-watch='sass --watch --compass ds_campaign.sass:ds_campaign.css'

# Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
